import os
import json
from src.engine.settings import QUESTIONS_DIR

# 25 questions per subject (Math, Biology, Chemistry, Physics, Science, English, History, Geography, CS)
DEFAULT_BANKS = {
    "mathematics": [
        {"question": "Solve: 7x - 5 = 16. What is x?", "choices": ["3", "2", "4", "5"], "answer": "3"},
        {"question": "What is the square root of 225?", "choices": ["15", "12", "25", "16"], "answer": "15"},
        {"question": "What is the area of a circle with radius 7? (Use pi = 22/7)", "choices": ["154", "44", "88", "49"], "answer": "154"},
        {"question": "Solve for x: x/4 + 6 = 11.", "choices": ["20", "15", "24", "16"], "answer": "20"},
        {"question": "What is 15% of 200?", "choices": ["30", "20", "15", "40"], "answer": "30"},
        {"question": "What is the value of 3^4 (3 to the power of 4)?", "choices": ["81", "27", "64", "12"], "answer": "81"},
        {"question": "In a right-angled triangle, if base = 3 and height = 4, what is the hypotenuse?", "choices": ["5", "6", "7", "8"], "answer": "5"},
        {"question": "Solve: 12 + 4 * (10 - 2^3).", "choices": ["20", "32", "16", "24"], "answer": "20"},
        {"question": "What is the perimeter of a rectangle with length 12 and width 5?", "choices": ["34", "17", "60", "30"], "answer": "34"},
        {"question": "If a card is drawn from a deck of 52 cards, what is the probability of getting an Ace?", "choices": ["1/13", "1/4", "1/52", "4/13"], "answer": "1/13"},
        {"question": "Convert 3/8 into a decimal.", "choices": ["0.375", "0.333", "0.625", "0.875"], "answer": "0.375"},
        {"question": "What is the sum of angles inside a hexagon?", "choices": ["720 degrees", "540 degrees", "360 degrees", "180 degrees"], "answer": "720 degrees"},
        {"question": "What is the greatest common divisor (GCD) of 36 and 48?", "choices": ["12", "6", "18", "8"], "answer": "12"},
        {"question": "Find the average of: 14, 18, 22, 26.", "choices": ["20", "18", "21", "22"], "answer": "20"},
        {"question": "If 3y = 4x + 10, and x = 5, what is y?", "choices": ["10", "5", "8", "6"], "answer": "10"},
        {"question": "What is the value of 9 * 8 - 6 * 4?", "choices": ["48", "36", "72", "24"], "answer": "48"},
        {"question": "What is the slope of the line passing through points (2,3) and (5,9)?", "choices": ["2", "3", "1.5", "4"], "answer": "2"},
        {"question": "Which of these is a prime number?", "choices": ["79", "87", "91", "95"], "answer": "79"},
        {"question": "If a train travels at 80 km/h, how far does it travel in 45 minutes?", "choices": ["60 km", "40 km", "70 km", "50 km"], "answer": "60 km"},
        {"question": "What is the value of (-5) * (-8) + (-12)?", "choices": ["28", "52", "-28", "40"], "answer": "28"},
        {"question": "What is the median of this data set: 5, 2, 9, 8, 3?", "choices": ["5", "3", "8", "4"], "answer": "5"},
        {"question": "Solve: 2^x = 128. What is x?", "choices": ["7", "6", "8", "9"], "answer": "7"},
        {"question": "A box contains 3 red, 4 blue, and 5 green balls. What is the ratio of red to green balls?", "choices": ["3:5", "3:4", "4:5", "3:12"], "answer": "3:5"},
        {"question": "Convert 135 degrees into radians.", "choices": ["3*pi/4", "pi/2", "5*pi/6", "2*pi/3"], "answer": "3*pi/4"},
        {"question": "What is the value of log2(64)?", "choices": ["6", "8", "5", "4"], "answer": "6"}
    ],
    
    "biology": [
        {"question": "Which cell organelle is known as the powerhouse of the cell?", "choices": ["Mitochondria", "Nucleus", "Ribosome", "Chloroplast"], "answer": "Mitochondria"},
        {"question": "What green pigment is used by plants to absorb light during photosynthesis?", "choices": ["Chlorophyll", "Carotenoid", "Xanthophyll", "Melanin"], "answer": "Chlorophyll"},
        {"question": "Which of the following is responsible for carrying oxygen in blood?", "choices": ["Hemoglobin", "Plasma", "White Blood Cells", "Platelets"], "answer": "Hemoglobin"},
        {"question": "What is the primary function of stomata in plant leaves?", "choices": ["Gas Exchange", "Water Absorption", "Nutrient Storage", "Photosynthesis"], "answer": "Gas Exchange"},
        {"question": "Which vitamin is synthesized in human skin when exposed to sunlight?", "choices": ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin E"], "answer": "Vitamin D"},
        {"question": "What is the double helix structure inside cells that holds genetic codes?", "choices": ["DNA", "RNA", "Protein", "Chromosome"], "answer": "DNA"},
        {"question": "Which chamber of the human heart pumps oxygenated blood to the body?", "choices": ["Left Ventricle", "Right Ventricle", "Left Atrium", "Right Atrium"], "answer": "Left Ventricle"},
        {"question": "What is the process of cell division that results in four daughter cells with half chromosomes?", "choices": ["Meiosis", "Mitosis", "Fission", "Budding"], "answer": "Meiosis"},
        {"question": "What part of the brain controls balance and muscle coordination?", "choices": ["Cerebellum", "Cerebrum", "Medulla", "Hypothalamus"], "answer": "Cerebellum"},
        {"question": "Which organism lacks a defined nucleus in its cell structures?", "choices": ["Bacteria", "Yeast", "Amoeba", "Fern"], "answer": "Bacteria"},
        {"question": "What is the primary site of nutrient absorption in the human digestive system?", "choices": ["Small Intestine", "Stomach", "Large Intestine", "Esophagus"], "answer": "Small Intestine"},
        {"question": "What type of blood vessel carries blood away from the heart?", "choices": ["Arteries", "Veins", "Capillaries", "Venules"], "answer": "Arteries"},
        {"question": "Which hormone regulates blood sugar levels in the human body?", "choices": ["Insulin", "Adrenaline", "Thyroxine", "Estrogen"], "answer": "Insulin"},
        {"question": "What term defines organisms that produce their own food?", "choices": ["Autotrophs", "Heterotrophs", "Decomposers", "Carnivores"], "answer": "Autotrophs"},
        {"question": "What is the main carbohydrate structural component of plant cell walls?", "choices": ["Cellulose", "Starch", "Glycogen", "Chitin"], "answer": "Cellulose"},
        {"question": "Which of these is the largest organ of the human body?", "choices": ["Skin", "Liver", "Lungs", "Brain"], "answer": "Skin"},
        {"question": "What is the basic functional unit of the kidney?", "choices": ["Nephron", "Neuron", "Alveoli", "Lobule"], "answer": "Nephron"},
        {"question": "Which animal group is characterized by having double-chambered hearts and dry scales?", "choices": ["Reptiles", "Amphibians", "Mammals", "Birds"], "answer": "Reptiles"},
        {"question": "What chemical messenger sends impulses across nerve synapses?", "choices": ["Neurotransmitter", "Hormone", "Enzyme", "Antigen"], "answer": "Neurotransmitter"},
        {"question": "In genetics, what term refers to having two different alleles for a trait?", "choices": ["Heterozygous", "Homozygous", "Dominant", "Recessive"], "answer": "Heterozygous"},
        {"question": "Which gas is released as a byproduct during plant photosynthesis?", "choices": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Water Vapor"], "answer": "Oxygen"},
        {"question": "What is the outer protective layer of virus structures called?", "choices": ["Capsid", "Membrane", "Envelope", "Shell"], "answer": "Capsid"},
        {"question": "Which blood type is known as the universal recipient?", "choices": ["AB Positive", "O Negative", "A Positive", "B Negative"], "answer": "AB Positive"},
        {"question": "What plant vascular tissue is responsible for transporting water upwards?", "choices": ["Xylem", "Phloem", "Cambium", "Cortex"], "answer": "Xylem"},
        {"question": "Which bone is the longest and strongest in the human skeleton?", "choices": ["Femur", "Tibia", "Humerus", "Pelvis"], "answer": "Femur"}
    ],
    
    "chemistry": [
        {"question": "What is the chemical symbol for Gold?", "choices": ["Au", "Ag", "Fe", "Gd"], "answer": "Au"},
        {"question": "What is the pH level of pure water at room temperature?", "choices": ["7", "0", "14", "5"], "answer": "7"},
        {"question": "Which subatomic particle carries a negative electrical charge?", "choices": ["Electron", "Proton", "Neutron", "Positron"], "answer": "Electron"},
        {"question": "What state of matter has a definite volume but no definite shape?", "choices": ["Liquid", "Solid", "Gas", "Plasma"], "answer": "Liquid"},
        {"question": "What is the most abundant gas in Earth's atmosphere?", "choices": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"], "answer": "Nitrogen"},
        {"question": "Which element has the atomic number 1?", "choices": ["Hydrogen", "Helium", "Oxygen", "Carbon"], "answer": "Hydrogen"},
        {"question": "What type of chemical bond involves sharing electron pairs between atoms?", "choices": ["Covalent Bond", "Ionic Bond", "Metallic Bond", "Hydrogen Bond"], "answer": "Covalent Bond"},
        {"question": "What law states that matter cannot be created or destroyed in a chemical reaction?", "choices": ["Law of Conservation of Mass", "Avogadro's Law", "Boyle's Law", "Charles's Law"], "answer": "Law of Conservation of Mass"},
        {"question": "What is the common name for Solid Carbon Dioxide?", "choices": ["Dry Ice", "Slush", "Quartz", "Chalk"], "answer": "Dry Ice"},
        {"question": "Which element is found in all organic chemical compounds?", "choices": ["Carbon", "Oxygen", "Nitrogen", "Silicon"], "answer": "Carbon"},
        {"question": "What is the chemical formula for Table Salt?", "choices": ["NaCl", "HCl", "NaOH", "KCl"], "answer": "NaCl"},
        {"question": "What substance speeds up a chemical reaction without being consumed?", "choices": ["Catalyst", "Inhibitor", "Reactant", "Solvent"], "answer": "Catalyst"},
        {"question": "What is the process of a solid turning directly into a gas?", "choices": ["Sublimation", "Evaporation", "Condensation", "Melting"], "answer": "Sublimation"},
        {"question": "What are vertical columns on the Periodic Table called?", "choices": ["Groups", "Periods", "Rows", "Alloys"], "answer": "Groups"},
        {"question": "Which gas has a rotten egg smell and is highly toxic?", "choices": ["Hydrogen Sulfide", "Sulfur Dioxide", "Ammonia", "Carbon Monoxide"], "answer": "Hydrogen Sulfide"},
        {"question": "What type of solution turns red litmus paper blue?", "choices": ["Basic / Alkaline", "Acidic", "Neutral", "Saline"], "answer": "Basic / Alkaline"},
        {"question": "What is the chemical formula for Baking Soda?", "choices": ["NaHCO3", "Na2CO3", "NaOH", "CaCO3"], "answer": "NaHCO3"},
        {"question": "Which metal is liquid at standard room temperature and pressure?", "choices": ["Mercury", "Gallium", "Lead", "Zinc"], "answer": "Mercury"},
        {"question": "What is the term for a reaction that releases heat energy to its surroundings?", "choices": ["Exothermic", "Endothermic", "Synthesis", "Decomposition"], "answer": "Exothermic"},
        {"question": "What is the charge of a neutron?", "choices": ["Neutral / Zero", "Positive", "Negative", "Double Positive"], "answer": "Neutral / Zero"},
        {"question": "Which halogen element is a purple-black solid at room temperature?", "choices": ["Iodine", "Chlorine", "Fluorine", "Bromine"], "answer": "Iodine"},
        {"question": "What is the main component of Natural Gas?", "choices": ["Methane", "Ethane", "Propane", "Butane"], "answer": "Methane"},
        {"question": "What defines an isotope of an element?", "choices": ["Different number of neutrons", "Different number of protons", "Different number of electrons", "Different charge"], "answer": "Different number of neutrons"},
        {"question": "What acid is found in vinegar?", "choices": ["Acetic Acid", "Citric Acid", "Hydrochloric Acid", "Formic Acid"], "answer": "Acetic Acid"},
        {"question": "What is the chemical symbol for Sodium?", "choices": ["Na", "So", "S", "Sd"], "answer": "Na"}
    ],
    
    "physics": [
        {"question": "What is the SI unit of Force?", "choices": ["Newton", "Joule", "Watt", "Pascal"], "answer": "Newton"},
        {"question": "What is the acceleration due to gravity on Earth's surface? (Approx.)", "choices": ["9.8 m/s^2", "1.6 m/s^2", "3.0 m/s^2", "12.5 m/s^2"], "answer": "9.8 m/s^2"},
        {"question": "According to Ohm's Law, what formula relates Voltage (V), Current (I), and Resistance (R)?", "choices": ["V = I * R", "I = V * R", "R = V * I", "V = I / R"], "answer": "V = I * R"},
        {"question": "What type of lens curves inward and disperses light rays?", "choices": ["Concave Lens", "Convex Lens", "Planar Lens", "Bifocal Lens"], "answer": "Concave Lens"},
        {"question": "What is the speed of light in a vacuum? (Approx.)", "choices": ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "3,000 km/s"], "answer": "300,000 km/s"},
        {"question": "What form of heat transfer occurs through electromagnetic waves?", "choices": ["Radiation", "Conduction", "Convection", "Induction"], "answer": "Radiation"},
        {"question": "Which law states that for every action, there is an equal and opposite reaction?", "choices": ["Newton's Third Law", "Newton's First Law", "Newton's Second Law", "Law of Inertia"], "answer": "Newton's Third Law"},
        {"question": "What type of energy is stored in an object due to its height position?", "choices": ["Gravitational Potential Energy", "Kinetic Energy", "Thermal Energy", "Chemical Energy"], "answer": "Gravitational Potential Energy"},
        {"question": "What frequency range defines sounds that humans cannot hear because they are too high?", "choices": ["Ultrasound (above 20kHz)", "Infrasound (below 20Hz)", "Supersonic", "Megasonic"], "answer": "Ultrasound (above 20kHz)"},
        {"question": "What is the SI unit of electrical charge?", "choices": ["Coulomb", "Ampere", "Volt", "Ohm"], "answer": "Coulomb"},
        {"question": "What term describes the bending of light rays as they pass from one medium to another?", "choices": ["Refraction", "Reflection", "Diffraction", "Dispersion"], "answer": "Refraction"},
        {"question": "What device converts mechanical kinetic energy into electrical energy?", "choices": ["Generator", "Motor", "Transformer", "Capacitor"], "answer": "Generator"},
        {"question": "Which of these materials is a good electrical insulator?", "choices": ["Rubber", "Copper", "Iron", "Aluminum"], "answer": "Rubber"},
        {"question": "What is the power of a machine that does 500 Joules of work in 5 seconds?", "choices": ["100 Watts", "2500 Watts", "50 Watts", "500 Watts"], "answer": "100 Watts"},
        {"question": "What type of wave is sound?", "choices": ["Longitudinal Wave", "Transverse Wave", "Electromagnetic Wave", "Shear Wave"], "answer": "Longitudinal Wave"},
        {"question": "What force acts opposite to the direction of motion of sliding objects?", "choices": ["Friction", "Gravity", "Tension", "Centripetal Force"], "answer": "Friction"},
        {"question": "What basic subatomic particle comprises a proton in modern particle physics?", "choices": ["Quarks", "Electrons", "Neutrinos", "Photons"], "answer": "Quarks"},
        {"question": "What term refers to the resistance of an object to change its state of motion?", "choices": ["Inertia", "Velocity", "Momentum", "Friction"], "answer": "Inertia"},
        {"question": "What is the SI unit of Pressure?", "choices": ["Pascal", "Newton", "Bar", "Torr"], "answer": "Pascal"},
        {"question": "What is the absolute zero temperature in Celsius? (Approx.)", "choices": ["-273 degrees C", "0 degrees C", "-100 degrees C", "-460 degrees C"], "answer": "-273 degrees C"},
        {"question": "What is the term for a material that has zero electrical resistance at low temperatures?", "choices": ["Superconductor", "Semiconductor", "Super-insulator", "Electromagnet"], "answer": "Superconductor"},
        {"question": "What type of nuclear reaction powers the Sun?", "choices": ["Nuclear Fusion", "Nuclear Fission", "Radioactive Decay", "Spontaneous Combustion"], "answer": "Nuclear Fusion"},
        {"question": "What is the product of mass and velocity of an object?", "choices": ["Momentum", "Force", "Work", "Kinetic Energy"], "answer": "Momentum"},
        {"question": "Which of Kepler's laws states that planetary orbits are ellipses?", "choices": ["First Law", "Second Law", "Third Law", "Law of Harmonies"], "answer": "First Law"},
        {"question": "What basic instrument is used to measure electrical current?", "choices": ["Ammeter", "Voltmeter", "Galvanometer", "Ohmmeter"], "answer": "Ammeter"}
    ],
    
    "science": [
        {"question": "Which planet is closest to the Sun?", "choices": ["Mercury", "Venus", "Mars", "Earth"], "answer": "Mercury"},
        {"question": "What is the outermost layer of Earth's atmosphere?", "choices": ["Exosphere", "Troposphere", "Stratosphere", "Mesosphere"], "answer": "Exosphere"},
        {"question": "What is the approximate age of the Universe in billions of years?", "choices": ["13.8 billion", "4.6 billion", "100 billion", "1.5 billion"], "answer": "13.8 billion"},
        {"question": "What phase of the water cycle involves water vapor turning back into liquid clouds?", "choices": ["Condensation", "Evaporation", "Precipitation", "Transpiration"], "answer": "Condensation"},
        {"question": "What type of rock is formed by cooling volcanic lava?", "choices": ["Igneous Rock", "Sedimentary Rock", "Metamorphic Rock", "Quartzite"], "answer": "Igneous Rock"},
        {"question": "Which planet has the most visible rings in our solar system?", "choices": ["Saturn", "Jupiter", "Uranus", "Neptune"], "answer": "Saturn"},
        {"question": "What is the name of the nearest spiral galaxy to our Milky Way?", "choices": ["Andromeda", "Triangulum", "Large Magellanic Cloud", "Orion Galaxy"], "answer": "Andromeda"},
        {"question": "Which geological boundary occurs where tectonic plates slide past each other horizontally?", "choices": ["Transform Boundary", "Convergent Boundary", "Divergent Boundary", "Subduction Zone"], "answer": "Transform Boundary"},
        {"question": "What causes the ocean tides on Earth?", "choices": ["Gravitational pull of the Moon and Sun", "Wind currents", "Rotation of Earth", "Underwater earthquakes"], "answer": "Gravitational pull of the Moon and Sun"},
        {"question": "What layer of Earth is composed of molten liquid iron and nickel?", "choices": ["Outer Core", "Inner Core", "Mantle", "Crust"], "answer": "Outer Core"},
        {"question": "What is the primary energy source driving Earth's climate system?", "choices": ["The Sun", "Geothermal Core", "Tidal friction", "Wind energy"], "answer": "The Sun"},
        {"question": "What atmospheric gas protects Earth from harmful ultraviolet radiation?", "choices": ["Ozone", "Oxygen", "Nitrogen", "Methane"], "answer": "Ozone"},
        {"question": "What defines a solar eclipse?", "choices": ["Moon passes between Sun and Earth", "Earth passes between Sun and Moon", "Sun passes between Earth and Moon", "Venus passes in front of Sun"], "answer": "Moon passes between Sun and Earth"},
        {"question": "What is the main component of stars like the Sun?", "choices": ["Hydrogen", "Helium", "Oxygen", "Iron"], "answer": "Hydrogen"},
        {"question": "Which planet is known as the Red Planet?", "choices": ["Mars", "Venus", "Jupiter", "Mercury"], "answer": "Mars"},
        {"question": "What is the name of the giant storm on Jupiter that has lasted for centuries?", "choices": ["Great Red Spot", "Great Dark Spot", "Eye of Jupiter", "Solar Cyclone"], "answer": "Great Red Spot"},
        {"question": "What geological instrument is used to detect and record earthquakes?", "choices": ["Seismograph", "Barometer", "Anemometer", "Richter Scale"], "answer": "Seismograph"},
        {"question": "What is the term for a star that has collapsed under its own gravity to form a singularity?", "choices": ["Black Hole", "Neutron Star", "White Dwarf", "Red Giant"], "answer": "Black Hole"},
        {"question": "What layer of Earth contains the tectonic plates?", "choices": ["Lithosphere", "Asthenosphere", "Mesosphere", "Crust"], "answer": "Lithosphere"},
        {"question": "What type of cloud is associated with heavy rainstorms and thunderstorms?", "choices": ["Cumulonimbus", "Cirrus", "Stratus", "Altocumulus"], "answer": "Cumulonimbus"},
        {"question": "What is the unit used to measure distances between stars and galaxies?", "choices": ["Light-year", "Kilometer", "Astronomical Unit", "Parsec"], "answer": "Light-year"},
        {"question": "What is the coldest planet in our solar system?", "choices": ["Uranus", "Neptune", "Saturn", "Pluto"], "answer": "Uranus"},
        {"question": "What is the process where liquid water turns into water vapor gas?", "choices": ["Evaporation", "Condensation", "Sublimation", "Melting"], "answer": "Evaporation"},
        {"question": "How long does it take for Earth to complete one orbit around the Sun?", "choices": ["365.25 days", "24 hours", "30 days", "360 days"], "answer": "365.25 days"},
        {"question": "What describes a meteoroid that has successfully landed on Earth's surface?", "choices": ["Meteorite", "Meteor", "Asteroid", "Comet"], "answer": "Meteorite"}
    ],
    
    "english": [
        {"question": "What part of speech is used to describe a verb, adjective, or another adverb?", "choices": ["Adverb", "Noun", "Pronoun", "Preposition"], "answer": "Adverb"},
        {"question": "Which word is an antonym of 'Generous'?", "choices": ["Stingy", "Kind", "Selfless", "Helpful"], "answer": "Stingy"},
        {"question": "What spelling is correct for the word meaning 'essential/extremely important'?", "choices": ["Necessary", "Necassary", "Neccessary", "Necesary"], "answer": "Necessary"},
        {"question": "Which of these sentences is written in the passive voice?", "choices": ["The cake was baked by Sarah.", "Sarah baked the cake.", "Sarah is baking the cake.", "Sarah will bake a cake."], "answer": "The cake was baked by Sarah."},
        {"question": "What is a figure of speech that directly compares two things using 'like' or 'as'?", "choices": ["Simile", "Metaphor", "Personification", "Hyperbole"], "answer": "Simile"},
        {"question": "Choose the correct pronoun: 'Neither of the boys brought ___ homework.'", "choices": ["his", "their", "they're", "its"], "answer": "his"},
        {"question": "Identify the conjunction in: 'I wanted to walk in the park, but it started raining.'", "choices": ["but", "to", "in", "it"], "answer": "but"},
        {"question": "Which literary term refers to the main message or underlying meaning of a story?", "choices": ["Theme", "Plot", "Setting", "Climax"], "answer": "Theme"},
        {"question": "What is the term for words that sound the same but have different meanings and spellings?", "choices": ["Homophones", "Synonyms", "Antonyms", "Acronyms"], "answer": "Homophones"},
        {"question": "Which spelling is correct?", "choices": ["Receive", "Recieve", "Receve", "Receivee"], "answer": "Receive"},
        {"question": "What does the root word 'bene' mean, as in 'beneficial' or 'benevolent'?", "choices": ["Good / Well", "Bad", "Under", "Time"], "answer": "Good / Well"},
        {"question": "Identify the verb tense: 'By next week, she will have completed the project.'", "choices": ["Future Perfect", "Future Simple", "Present Perfect", "Past Perfect"], "answer": "Future Perfect"},
        {"question": "What is a person, place, thing, or abstract idea called in grammar?", "choices": ["Noun", "Adjective", "Preposition", "Conjunction"], "answer": "Noun"},
        {"question": "Which of these is a metaphor?", "choices": ["Time is a thief.", "He was as brave as a lion.", "The leaves danced in the wind.", "I have a million things to do."], "answer": "Time is a thief."},
        {"question": "What punctuation mark is used to connect independent clauses without a conjunction?", "choices": ["Semicolon", "Comma", "Colon", "Dash"], "answer": "Semicolon"},
        {"question": "What is the term for a word formed by combining and shortening two words, like 'don't'?", "choices": ["Contraction", "Abbreviation", "Acronym", "Prefix"], "answer": "Contraction"},
        {"question": "Which word is a synonym for 'Meticulous'?", "choices": ["Precise", "Careless", "Lazy", "Unorganized"], "answer": "Precise"},
        {"question": "What figure of speech gives human traits to non-human things?", "choices": ["Personification", "Alliteration", "Onomatopoeia", "Metaphor"], "answer": "Personification"},
        {"question": "What is the error in: 'Each of the students are ready.'?", "choices": ["Subject-verb agreement (should be 'is')", "Pronoun error", "Run-on sentence", "Comma splice"], "answer": "Subject-verb agreement (should be 'is')"},
        {"question": "What is the name of a group of words that contains a subject and a verb but cannot stand alone?", "choices": ["Dependent Clause", "Independent Clause", "Prepositional Phrase", "Gerund"], "answer": "Dependent Clause"},
        {"question": "Which word is spelled correctly?", "choices": ["Accommodation", "Accomodation", "Acommodation", "Acomodation"], "answer": "Accommodation"},
        {"question": "What root word means 'life', as in 'biology' or 'biography'?", "choices": ["bio", "geo", "chrono", "tele"], "answer": "bio"},
        {"question": "What is the climax of a story plot?", "choices": ["The peak turning point of tension", "The introduction of characters", "The resolution of conflict", "The background explanation"], "answer": "The peak turning point of tension"},
        {"question": "Identify the preposition in: 'The keys are under the table.'", "choices": ["under", "are", "the", "table"], "answer": "under"},
        {"question": "What term describes the attitude or feeling of a writer conveyed through word choice?", "choices": ["Tone", "Mood", "Genre", "Voice"], "answer": "Tone"}
    ],
    
    "history": [
        {"question": "Who was the first President of the United States?", "choices": ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], "answer": "George Washington"},
        {"question": "What empire was ruled by Julius Caesar?", "choices": ["Roman Empire", "Greek Empire", "Persian Empire", "Ottoman Empire"], "answer": "Roman Empire"},
        {"question": "In what year did World War II end?", "choices": ["1945", "1918", "1939", "1950"], "answer": "1945"},
        {"question": "Which civilization built the Great Pyramid of Giza?", "choices": ["Ancient Egyptians", "Ancient Romans", "Mesopotamians", "Aztecs"], "answer": "Ancient Egyptians"},
        {"question": "What document declared American independence from Great Britain in 1776?", "choices": ["Declaration of Independence", "The Constitution", "Bill of Rights", "Magna Carta"], "answer": "Declaration of Independence"},
        {"question": "Who was the famous French female military leader during the Hundred Years' War?", "choices": ["Joan of Arc", "Marie Antoinette", "Catherine the Great", "Queen Elizabeth"], "answer": "Joan of Arc"},
        {"question": "Which ancient trade route connected China to the Mediterranean region?", "choices": ["Silk Road", "Amber Road", "Spice Route", "Trans-Saharan Path"], "answer": "Silk Road"},
        {"question": "What event sparked the beginning of World War I in 1914?", "choices": ["Assassination of Archduke Franz Ferdinand", "Invasion of Poland", "Sinking of Lusitania", "Treaty of Versailles"], "answer": "Assassination of Archduke Franz Ferdinand"},
        {"question": "Who was the leader of the Mongol Empire in the 13th century?", "choices": ["Genghis Khan", "Kublai Khan", "Alexander the Great", "Charlemagne"], "answer": "Genghis Khan"},
        {"question": "What document signed in 1215 limited the power of the English King?", "choices": ["Magna Carta", "Mayflower Compact", "Declaration of Rights", "Common Sense"], "answer": "Magna Carta"},
        {"question": "Which country did the Renaissance begin in during the 14th century?", "choices": ["Italy", "France", "England", "Spain"], "answer": "Italy"},
        {"question": "What was the main purpose of the Berlin Wall built in 1961?", "choices": ["To divide East and West Berlin", "To guard borders from invasion", "To serve as a monument", "To control highway traffic"], "answer": "To divide East and West Berlin"},
        {"question": "Who sailed the ocean blue in 1492, landing in the Americas?", "choices": ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "Amerigo Vespucci"], "answer": "Christopher Columbus"},
        {"question": "What civilization constructed the ancient city of Machu Picchu?", "choices": ["Inca Empire", "Aztec Empire", "Mayan Empire", "Toltecs"], "answer": "Inca Empire"},
        {"question": "What was the name of the global economic downturn of the 1930s?", "choices": ["The Great Depression", "The Industrial Crash", "The Tulip Mania", "The Inflation Crisis"], "answer": "The Great Depression"},
        {"question": "Which US President issued the Emancipation Proclamation in 1863?", "choices": ["Abraham Lincoln", "George Washington", "Andrew Jackson", "Ulysses S. Grant"], "answer": "Abraham Lincoln"},
        {"question": "What code of laws was written by an ancient Babylonian king around 1750 BC?", "choices": ["Code of Hammurabi", "Justin Law", "Twelve Tables", "Draconian Code"], "answer": "Code of Hammurabi"},
        {"question": "Who was the first female Prime Minister of the United Kingdom?", "choices": ["Margaret Thatcher", "Theresa May", "Queen Victoria", "Angela Merkel"], "answer": "Margaret Thatcher"},
        {"question": "What ancient Greek city-state was known for its militaristic society?", "choices": ["Sparta", "Athens", "Thebes", "Corinth"], "answer": "Sparta"},
        {"question": "What movement split the Western Church into Catholic and Protestant branches in the 16th century?", "choices": ["Protestant Reformation", "Great Schism", "Counter-Reformation", "Enlightenment"], "answer": "Protestant Reformation"},
        {"question": "What was the name of the first artificial satellite launched into space by the USSR in 1957?", "choices": ["Sputnik 1", "Vostok 1", "Apollo 11", "Explorer 1"], "answer": "Sputnik 1"},
        {"question": "What revolution overthrew the French monarchy in 1789?", "choices": ["French Revolution", "Glorious Revolution", "Industrial Revolution", "Russian Revolution"], "answer": "French Revolution"},
        {"question": "Who wrote the 'I Have a Dream' speech delivered during the 1963 March on Washington?", "choices": ["Martin Luther King Jr.", "Malcolm X", "John F. Kennedy", "Rosa Parks"], "answer": "Martin Luther King Jr."},
        {"question": "What ancient empire built the Colosseum in Rome?", "choices": ["Roman Empire", "Byzantine Empire", "Macedonian Empire", "Persian Empire"], "answer": "Roman Empire"},
        {"question": "Which country developed the first gunpowder weapons in history?", "choices": ["China", "India", "Egypt", "Greece"], "answer": "China"}
    ],
    
    "geography": [
        {"question": "What is the capital city of France?", "choices": ["Paris", "London", "Berlin", "Rome"], "answer": "Paris"},
        {"question": "What is the largest ocean on Earth?", "choices": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "answer": "Pacific Ocean"},
        {"question": "Which continent contains the Sahara Desert?", "choices": ["Africa", "Asia", "South America", "Australia"], "answer": "Africa"},
        {"question": "What is the longest river in the world?", "choices": ["Nile River", "Amazon River", "Yangtze River", "Mississippi River"], "answer": "Nile River"},
        {"question": "What is the highest mountain peak in the world?", "choices": ["Mount Everest", "K2", "Kilimanjaro", "Mount Fuji"], "answer": "Mount Everest"},
        {"question": "What country has the largest landmass area?", "choices": ["Russia", "Canada", "China", "United States"], "answer": "Russia"},
        {"question": "Which of these is the capital city of Australia?", "choices": ["Canberra", "Sydney", "Melbourne", "Brisbane"], "answer": "Canberra"},
        {"question": "What is the smallest country in the world by land area?", "choices": ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], "answer": "Vatican City"},
        {"question": "What is the capital city of Japan?", "choices": ["Tokyo", "Kyoto", "Osaka", "Seoul"], "answer": "Tokyo"},
        {"question": "Which sea separates Europe from Africa?", "choices": ["Mediterranean Sea", "Red Sea", "Black Sea", "Caribbean Sea"], "answer": "Mediterranean Sea"},
        {"question": "What is the largest hot desert in North America?", "choices": ["Chihuahuan Desert", "Mojave Desert", "Sonoran Desert", "Great Basin Desert"], "answer": "Chihuahuan Desert"},
        {"question": "Which country is shaped like a boot in Southern Europe?", "choices": ["Italy", "Greece", "Spain", "Portugal"], "answer": "Italy"},
        {"question": "What is the capital city of Canada?", "choices": ["Ottawa", "Toronto", "Vancouver", "Montreal"], "answer": "Ottawa"},
        {"question": "Which imaginary line divides Earth into Northern and Southern hemispheres?", "choices": ["Equator", "Prime Meridian", "Tropic of Cancer", "Antarctic Circle"], "answer": "Equator"},
        {"question": "What mountain range separates Europe from Asia?", "choices": ["Ural Mountains", "Alps", "Himalayas", "Andes"], "answer": "Ural Mountains"},
        {"question": "What country contains the cities Rio de Janeiro and Sao Paulo?", "choices": ["Brazil", "Argentina", "Mexico", "Colombia"], "answer": "Brazil"},
        {"question": "What is the capital city of Spain?", "choices": ["Madrid", "Barcelona", "Lisbon", "Seville"], "answer": "Madrid"},
        {"question": "What is the deepest point in the world's oceans?", "choices": ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Sunda Trench"], "answer": "Mariana Trench"},
        {"question": "Which US state is an island chain in the Pacific Ocean?", "choices": ["Hawaii", "Alaska", "California", "Florida"], "answer": "Hawaii"},
        {"question": "What is the capital city of India?", "choices": ["New Delhi", "Mumbai", "Kolkata", "Delhi"], "answer": "New Delhi"},
        {"question": "What major river flows through London, England?", "choices": ["River Thames", "River Seine", "Danube", "Rhine"], "answer": "River Thames"},
        {"question": "Which country is bordered by both the Atlantic and Pacific oceans?", "choices": ["United States", "Brazil", "South Africa", "Spain"], "answer": "United States"},
        {"question": "What is the capital city of Germany?", "choices": ["Berlin", "Munich", "Frankfurt", "Hamburg"], "answer": "Berlin"},
        {"question": "Which continent contains the South Pole?", "choices": ["Antarctica", "Australia", "South America", "Europe"], "answer": "Antarctica"},
        {"question": "What is the capital city of Egypt?", "choices": ["Cairo", "Alexandria", "Giza", "Luxor"], "answer": "Cairo"}
    ],
    
    "computer_science": [
        {"question": "What is the decimal equivalent of the binary number 1011?", "choices": ["11", "9", "13", "15"], "answer": "11"},
        {"question": "What does CPU stand for?", "choices": ["Central Processing Unit", "Computer Personal Unit", "Central Power Utility", "Control Processing Unit"], "answer": "Central Processing Unit"},
        {"question": "What programming language is widely known for its snake logo and readability?", "choices": ["Python", "Java", "C++", "HTML"], "answer": "Python"},
        {"question": "What basic data structure works on a Last-In, First-Out (LIFO) model?", "choices": ["Stack", "Queue", "Array", "Linked List"], "answer": "Stack"},
        {"question": "What does HTML stand for?", "choices": ["HyperText Markup Language", "HighTech Modern Language", "HyperText Memory Link", "Home Tool Markup Language"], "answer": "HyperText Markup Language"},
        {"question": "Which sorting algorithm operates by repeatedly swapping adjacent elements if they are in the wrong order?", "choices": ["Bubble Sort", "Quick Sort", "Merge Sort", "Insertion Sort"], "answer": "Bubble Sort"},
        {"question": "What type of loop repeats code while a given boolean condition remains True?", "choices": ["While Loop", "For Loop", "If Statement", "Switch Case"], "answer": "While Loop"},
        {"question": "What is the keyword used in Python to define a function?", "choices": ["def", "func", "function", "define"], "answer": "def"},
        {"question": "What term defines a bug or error in computer software?", "choices": ["Bug", "Virus", "Glitch", "Patch"], "answer": "Bug"},
        {"question": "What is the size of 1 Byte in bits?", "choices": ["8 bits", "4 bits", "16 bits", "32 bits"], "answer": "8 bits"},
        {"question": "Which protocol is used to fetch web pages securely from a web server?", "choices": ["HTTPS", "FTP", "SMTP", "HTTP"], "answer": "HTTPS"},
        {"question": "What type of variable can store only True or False values?", "choices": ["Boolean", "Integer", "String", "Float"], "answer": "Boolean"},
        {"question": "What does RAM stand for?", "choices": ["Random Access Memory", "Read Alternate Memory", "Rapid Action Module", "Run Active Memory"], "answer": "Random Access Memory"},
        {"question": "In Python, how do you index the last element of a list named 'my_list'?", "choices": ["my_list[-1]", "my_list[last]", "my_list[len(my_list)]", "my_list[0]"], "answer": "my_list[-1]"},
        {"question": "What database query language is used to perform relational operations?", "choices": ["SQL", "NoSQL", "Python", "MongoDB"], "answer": "SQL"},
        {"question": "What does IP stand for in network address schemas?", "choices": ["Internet Protocol", "Information Path", "Internal Point", "Intranet Port"], "answer": "Internet Protocol"},
        {"question": "What logic gate outputs True only if both inputs are True?", "choices": ["AND Gate", "OR Gate", "XOR Gate", "NOT Gate"], "answer": "AND Gate"},
        {"question": "Which data structure uses keys to map direct elements values?", "choices": ["Dictionary / Hash Map", "Set", "Tuple", "Array"], "answer": "Dictionary / Hash Map"},
        {"question": "What is the decimal value of the hexadecimal digit 'A'?", "choices": ["10", "11", "9", "12"], "answer": "10"},
        {"question": "What command line command is used in Git to copy an existing repository?", "choices": ["git clone", "git fork", "git pull", "git copy"], "answer": "git clone"},
        {"question": "What describes a step-by-step set of operations to solve a problem?", "choices": ["Algorithm", "Variable", "Compiler", "Compiler Directive"], "answer": "Algorithm"},
        {"question": "What is the index of the first item in arrays/lists in most programming languages?", "choices": ["0", "1", "-1", "IndexError"], "answer": "0"},
        {"question": "What programming language compile-time helper translates source code into machine code?", "choices": ["Compiler", "Interpreter", "Linker", "Debugger"], "answer": "Compiler"},
        {"question": "What is the primary function of a Router in networking?", "choices": ["Direct data packets between networks", "Store files in memory", "Protect systems from malware", "Compile programs"], "answer": "Direct data packets between networks"},
        {"question": "What is the output of 'print(5 // 2)' in Python?", "choices": ["2", "2.5", "3", "1"], "answer": "2"}
    ]
}

def generate_default_questions():
    """Generates default subject JSON question banks if they are absent."""
    os.makedirs(QUESTIONS_DIR, exist_ok=True)
    
    for subject, q_list in DEFAULT_BANKS.items():
        file_path = os.path.join(QUESTIONS_DIR, f"{subject}.json")
        if not os.path.exists(file_path):
            try:
                with open(file_path, "w") as f:
                    json.dump(q_list, f, indent=4)
                print(f"Generated default question bank: {file_path}")
            except Exception as e:
                print(f"Failed to generate question bank {subject}: {e}")
